<template><div><h4 id="参考文章" tabindex="-1"><a class="header-anchor" href="#参考文章"><span>参考文章</span></a></h4>
<p>https://blog.csdn.net/job_csdn/article/details/128136490</p>
<h4 id="_1-下载linux版本的jdk1-8" tabindex="-1"><a class="header-anchor" href="#_1-下载linux版本的jdk1-8"><span>1. 下载Linux版本的JDK1.8</span></a></h4>
<p>https://www.oracle.com/java/technologies/downloads/#java8</p>
<p>一定要下载<em><strong>对应操作架构</strong></em>的JDK，否则会报错：可通过uname -a 命令查看</p>
<p><img src="@source/notes/Java/麒麟操作系统安装JAVA环境/assets/查看kylin系统版本.png" alt="Linux系统版本查看"></p>
<h4 id="_2-将下载好的安装包xx-tar-gz放到安装目录" tabindex="-1"><a class="header-anchor" href="#_2-将下载好的安装包xx-tar-gz放到安装目录"><span>2. 将下载好的安装包xx.tar.gz放到安装目录</span></a></h4>
<div class="language-sh line-numbers-mode" data-ext="sh" data-title="sh"><button class="copy" title="复制代码" data-copied="已复制"></button><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"># 例如放到如下目录</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">/usr/local/jdk8</span></span></code></pre>

<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><h4 id="_3-配置环境变量" tabindex="-1"><a class="header-anchor" href="#_3-配置环境变量"><span>3. 配置环境变量</span></a></h4>
<div class="language-sh line-numbers-mode" data-ext="sh" data-title="sh"><button class="copy" title="复制代码" data-copied="已复制"></button><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"># 1. 打开/etc/profile文件</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">vim</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> /etc/profile</span></span>
<span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"># 2. 配置环境变量</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">export</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> JAVA_HOME</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> = /</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">usr</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">/</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">local</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">/</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">jdk8</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">/</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">jdk1</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">.</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">8</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">.</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">0_361</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">export</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> PATH</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> = </span><span style="--shiki-light:#999999;--shiki-dark:#666666">${</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">JAVA_HOME</span><span style="--shiki-light:#999999;--shiki-dark:#666666">}</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">/</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">bin</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">:</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">$PATH</span></span>
<span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">export</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A"> CLASSPATH</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> = .:</span><span style="--shiki-light:#999999;--shiki-dark:#666666">${</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">JAVA_HOME</span><span style="--shiki-light:#999999;--shiki-dark:#666666">}</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE">/</span><span style="--shiki-light:#B07D48;--shiki-dark:#BD976A">lib</span></span></code></pre>

<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h4 id="_4-测试" tabindex="-1"><a class="header-anchor" href="#_4-测试"><span>4. 测试</span></a></h4>
<div class="language-sh line-numbers-mode" data-ext="sh" data-title="sh"><button class="copy" title="复制代码" data-copied="已复制"></button><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">java</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> -version</span></span></code></pre>

<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>如果出现如下情况</p>
<p><img src="@source/notes/Java/麒麟操作系统安装JAVA环境/assets/java安装权限问题.png" alt="java安装权限问题"></p>
<p>需要设置文件/目录权限</p>
<div class="language-sh line-numbers-mode" data-ext="sh" data-title="sh"><button class="copy" title="复制代码" data-copied="已复制"></button><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"># 提升权限命令  【用于改变文件或目录的访问权限】</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">chmod</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 775</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> [提示Permission </span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">denied的目录路径]</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> </span></span>
<span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD"># 权限详解 ： https://developer.aliyun.com/article/19350</span></span></code></pre>

<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>再次测试</p>
<div class="language-sh line-numbers-mode" data-ext="sh" data-title="sh"><button class="copy" title="复制代码" data-copied="已复制"></button><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">java</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> -version</span><span style="--shiki-light:#999999;--shiki-dark:#666666">;</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">java</span><span style="--shiki-light:#999999;--shiki-dark:#666666">;</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">javac</span><span style="--shiki-light:#999999;--shiki-dark:#666666">;</span></span></code></pre>

<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


