<template><div><h1 id="opensoftware-bat" tabindex="-1"><a class="header-anchor" href="#opensoftware-bat"><span>OpenSoftWare.bat</span></a></h1>
<div class="language-bat line-numbers-mode" data-ext="bat" data-title="bat"><button class="copy" title="复制代码" data-copied="已复制"></button><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#AB5959;--shiki-dark:#CB7676">    @</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">echo</span><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375"> off</span></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">    start</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> /d </span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">D:\Program Files (x86)\Tencent\WeChat\</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> WeChat.exe</span></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">    start</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> /d </span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">D:\Program Files (x86)\Tencent\WeChat\</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> WeChat.exe</span></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">    start</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> /d </span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">D:\Program Files (x86)\Tencent\QQ\Bin\</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> QQ.exe</span></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">    start</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> /d </span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">D:\Program Files\JetBrains\IntelliJ IDEA 2020.3.4\bin\</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> idea64.exe</span></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">    start</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> /d </span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">D:\Program Files\PremiumSoft\Navicat Premium 15\</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> navicat.exe</span></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">    start</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> /d </span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">D:\Program Files\Snipaste-1.16.2-x64\</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#393A34;--shiki-dark:#DBD7CAEE"> Snipaste.exe</span></span>
<span class="line"><span style="--shiki-light:#1E754F;--shiki-dark:#4D9375">    exit</span></span></code></pre>

<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


